### ISSUE TITLE
Code snippet not working properly

### ISSUE THREAD

**Issue by shahriarhossain** [madskristensen/GruntSnippetPack#1]
### Installed product versions
- Visual Studio Enterprise 2015 Update 2
- This extension:  Grunt Snippet Pack v1.1.5
### Description

Not all code snippet are working properly. If I try grunt tab tab it works. but inside the snippet if I try pkg or other snippet nothing appears.
### Current behavior

pkg or other snippet that you have provided not appearing inside grunt snippet.
![untitled](https://cloud.githubusercontent.com/assets/6463320/16770116/49eede0e-4800-11e6-95b7-c51e5b964a52.png)

If I try pkg outside the grunt snippet that works.
![untitled2](https://cloud.githubusercontent.com/assets/6463320/16770218/b4997886-4800-11e6-9435-1bd95733bc41.png)

However, Inside the grunt snippet when pressing CTRL+K, CTRL+X do show me the the grunt snippet pack, from there I can select the pkg or other snippet and everything works. 
![untitled3](https://cloud.githubusercontent.com/assets/6463320/16770287/289c81b0-4801-11e6-998b-8e1f43f77d49.png)
### Expected behavior

I am expecting this behavior. i.e. typing grunt tab tab will give me the grunt snippet and then typing pkg tab tab will give me the snippet of pkg. 
![animation](https://cloud.githubusercontent.com/assets/6463320/16770326/613d16c4-4801-11e6-9706-67f532942dbb.gif)

**Comment by shahriarhossain** [comment]
@madskristensen : any update on this? seems like a VS tooling issue.

**Comment by madskristensen** [comment]
This is a bug in the .JS editor in Visual Studio and not an issue that can be fixed by this template pack.

/cc @billti @bowdenk7
